### ISSUE TITLE
OnPrime Flyte Binary Values file Link not found (404 Error)

### ISSUE THREAD

**Issue by DevendraJohari24** [davidmirror-ops/flyte-the-hard-way#16]
curl -sL https://raw.githubusercontent.com/davidmirror-ops/flyte-the-hard-way/main/docs/on-premises/single-node/manifests/onprem-flyte-binary/values.yaml > onprem-flyte-binary-values.yaml
This link given in single node on-prem installation of flyte-binary didn't work

**Comment by davidmirror-ops** [comment]
Thanks for reporting
It has been fixed. Please check and report any other problem
