### ISSUE TITLE
Flyte-core UI not display the pipeline

### ISSUE THREAD

**Issue by ariefal891** [davidmirror-ops/flyte-the-hard-way#21]
Hello,

Can anyone help me, 
so i tried to install flyte-core in baremetal using microk8s, but everytime i run the code using pyflyte the UI results is failed to fetch data and not displaying anything.

error in UI : 
Failed to fetch data
invalid wire type 4 at offset 1
![Screenshot from 2024-10-14 15-24-10](https://github.com/user-attachments/assets/9f083378-8a48-4155-a67b-47ba031d1fed)
![flytenotrunning](https://github.com/user-attachments/assets/bfed653f-123f-4a58-b26b-1d91d0736a47)

**Comment by davidmirror-ops** [comment]
@ariefal891 Hey Arief
Sorry, I have the same problem and I guess you're not using Ingress but port-forwarding? Long story short, is should work if you use Ingress. 
Please let me know any question

**Comment by ariefal891** [comment]
Hai david

thanks for your response, I use port forwarding as described in the documentation.
okay I will try it using ingress, sorry I am still a newbie I will try it first but do you have any documentation recommendations that I can use as a reference to make it?

**Comment by ariefal891** [comment]
Hi David,

I really appreciate your help. After following your suggestion to use the Ingress, I was able to access the UI, and everything is now running successfully. Thank you so much!
